apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dpf-host-br
spec:
  desiredState:
    interfaces:
    - name: dpf-host-br
      type: linux-bridge
      state: up
      ipv4:
        dhcp: true
        enabled: true