---
- name: Install openBCE addons
  hosts: localhost
  vars_files:
    - ../bce.yaml
  tasks:
    - name: Install Cilium
      shell: ../sbin/cilium install

    - name: Install cert-manager
      shell: ../sbin/kubectl apply --kubeconfig {{ playbook_dir }}/config/kube.config -f https://github.com/cert-manager/cert-manager/releases/download/{{ certmanager_version }}/cert-manager.yaml
