---
- name: Install openBCE workers
  hosts: workers
  vars_files:
    - ../bce.yaml
  vars:
    - worker_join_cmd: "{{ lookup('file', 'config/worker-join.conf') }}"
  tasks:
    - name: Uninstall Old Kubernetes
      shell: kubeadm reset --force

    - name: Install Worker
      shell: "{{ worker_join_cmd }} --cri-socket unix:///run/containerd/containerd.sock"
