#!/bin/bash

# environment


if [ `id -u` -ne 0 ];then
	echo "bce-installer requires root permission"
	exit 1
fi

for i in "download" "prepare" "master" "worker" "addons"
do
  ansible-playbook -i invetory/hosts playbook/${i}.yaml

  if [ $? -ne 0 ]; then
      exit 1
  fi
done

