FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3-pip git ipmitool iproute2
RUN git clone -b 10.12.0 https://github.com/openstack/ironic-inspector /opt/ironic-inspector

RUN cd /opt/ironic-inspector && pip install -r requirements.txt && pip install .

RUN pip install PyMySQL

RUN rm -rf /opt/ironic-inspector
