FROM openbce/ironic:20.2.0

RUN apt-get update && apt-get install -y jq mysql-client curl

RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/bin/kubectl
RUN chmod +x /usr/bin/kubectl
